package com.inventoryapproval.inventoryapproval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleParameterDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "createdDate")
	private java.lang.String createdDate;

	@org.kie.api.definition.type.Label(value = "lastModifiedDate")
	private java.lang.String lastModifiedDate;

	@org.kie.api.definition.type.Label(value = "createdBy")
	private java.lang.String createdBy;

	@org.kie.api.definition.type.Label(value = "lastModifiedBy")
	private java.lang.String lastModifiedBy;

	public RuleParameterDto() {
	}

	private Long ruleParameterId;

	private String parameter;
	private String value;
	private int maxDC;
	private String ruleWeightage;
	private String description;

	private String displayGroupName;

	private Integer displayGroupIndex;

	private Integer displayFieldIndex;

	public Long getRuleParameterId() {
		return ruleParameterId;
	}
	public void setRuleParameterId(Long ruleParameterId) {
		this.ruleParameterId = ruleParameterId;
	}
	public String getParameter() {
		return parameter;
	}
	public void setParameter(String parameter) {
		this.parameter = parameter;
	}
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public int getMaxDC() {
		return maxDC;
	}
	public void setMaxDC(int maxDC) {
		this.maxDC = maxDC;
	}
	public String getRuleWeightage() {
		return ruleWeightage;
	}

	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getDisplayGroupName() {
		return displayGroupName;
	}
	public void setDisplayGroupName(String displayGroupName) {
		this.displayGroupName = displayGroupName;
	}
	public Integer getDisplayGroupIndex() {
		return displayGroupIndex;
	}
	public void setDisplayGroupIndex(Integer displayGroupIndex) {
		this.displayGroupIndex = displayGroupIndex;
	}
	public Integer getDisplayFieldIndex() {
		return displayFieldIndex;
	}
	public void setDisplayFieldIndex(Integer displayFieldIndex) {
		this.displayFieldIndex = displayFieldIndex;
	}
	public java.lang.String getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(java.lang.String createdDate) {
		this.createdDate = createdDate;
	}
	public java.lang.String getLastModifiedDate() {
		return this.lastModifiedDate;
	}
	public void setLastModifiedDate(java.lang.String lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	public java.lang.String getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(java.lang.String createdBy) {
		this.createdBy = createdBy;
	}
	public java.lang.String getLastModifiedBy() {
		return this.lastModifiedBy;
	}
	public void setLastModifiedBy(java.lang.String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}
	public RuleParameterDto(java.lang.String createdDate,
			java.lang.String lastModifiedDate, java.lang.String createdBy,
			java.lang.String lastModifiedBy, java.lang.Long ruleParameterId,
			java.lang.String parameter, java.lang.String value, int maxDC,
			java.lang.String ruleWeightage, java.lang.String description,
			java.lang.String displayGroupName,
			java.lang.Integer displayGroupIndex,
			java.lang.Integer displayFieldIndex) {
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.createdBy = createdBy;
		this.lastModifiedBy = lastModifiedBy;
		this.ruleParameterId = ruleParameterId;
		this.parameter = parameter;
		this.value = value;
		this.maxDC = maxDC;
		this.ruleWeightage = ruleWeightage;
		this.description = description;
		this.displayGroupName = displayGroupName;
		this.displayGroupIndex = displayGroupIndex;
		this.displayFieldIndex = displayFieldIndex;
	}
}